export const FEED_WS_ACTIONS = {
  INIT: 'FEED_WS_CONNECTION_START',
  CLOSE: 'FEED_WS_CONNECTION_CLOSE',
  SEND: 'FEED_WS_SEND_MESSAGE',
  OPEN: 'FEED_WS_CONNECTION_SUCCESS',
  CLOSED: 'FEED_WS_CONNECTION_CLOSED',
  ERROR: 'FEED_WS_CONNECTION_ERROR',
  MESSAGE: 'FEED_WS_GET_MESSAGE',
} as const;

export type TFeedWsActionTypes = (typeof FEED_WS_ACTIONS)[keyof typeof FEED_WS_ACTIONS];

export const PROFILE_WS_ACTIONS = {
  INIT: 'PROFILE_WS_CONNECTION_START',
  CLOSE: 'PROFILE_WS_CONNECTION_CLOSE',
  SEND: 'PROFILE_WS_SEND_MESSAGE',
  OPEN: 'PROFILE_WS_CONNECTION_SUCCESS',
  CLOSED: 'PROFILE_WS_CONNECTION_CLOSED',
  ERROR: 'PROFILE_WS_CONNECTION_ERROR',
  MESSAGE: 'PROFILE_WS_GET_MESSAGE',
} as const;

export type TProfileWsActionTypes =
  (typeof PROFILE_WS_ACTIONS)[keyof typeof PROFILE_WS_ACTIONS];
