declare const classNames: {
  readonly page: "page";
  readonly title: "title";
  readonly ordersColumn: "ordersColumn";
  readonly orderCard: "orderCard";
  readonly orderHeader: "orderHeader";
  readonly orderNumber: "orderNumber";
  readonly orderTime: "orderTime";
  readonly orderTitle: "orderTitle";
  readonly orderFooter: "orderFooter";
  readonly orderIngredients: "orderIngredients";
  readonly ingredientAvatar: "ingredientAvatar";
  readonly ingredientImage: "ingredientImage";
  readonly ingredientMore: "ingredientMore";
  readonly price: "price";
  readonly statsColumn: "statsColumn";
  readonly statusBlocks: "statusBlocks";
  readonly statusBlock: "statusBlock";
  readonly statusLists: "statusLists";
  readonly statusColumn: "statusColumn";
  readonly statusList: "statusList";
  readonly statusReady: "statusReady";
  readonly statusInProgress: "statusInProgress";
  readonly bigNumber: "bigNumber";
  readonly bigNumberBlock: "bigNumberBlock";
  readonly hint: "hint";
};
export default classNames;
